// Internal type definitions for the legacy NestJS-era service layer.
//
// Previously these carried class-validator + @nestjs/swagger decorators so the
// NestJS pipeline could validate request bodies and emit Swagger metadata.
// After the Hono migration, request/response validation lives in the oRPC Zod
// contracts (@web3insight/api-contract) and OpenAPI is generated by
// @orpc/openapi — so the decorators are dead weight that forced a
// reflect-metadata polyfill at every serverless entry.
//
// This file keeps the *type shapes* the services still depend on, but as
// plain TypeScript. Classes are retained for the `new XxxDto()` call sites in
// services/users.service.ts, services/rank.service.ts, services/repos.service.ts,
// and services/total.service.ts.
import {
  ActorsScopeType,
  ECO_ALL,
  type EcoNameFilter,
  StatsPeriod,
} from '@/data/dto/data.dto';
import {
  ActorDateItemDto,
  QueryTopActor,
  QueryTopStarRepo,
} from '@/data/dto/query.dto';
import type { api_analysis_users } from '@/db/schema';
type ApiAnalysisUsers = typeof api_analysis_users.$inferSelect;

export class GetTotalReqDto {
  eco_name: EcoNameFilter = ECO_ALL;
}

export class GetRepoInfoDto {
  repo_id: number = 0;
}

export class GetActorsTotalReqDto extends GetTotalReqDto {
  scope: ActorsScopeType = ActorsScopeType.ALL;
}

export class TotalDto {
  total: number = 0;
}

export class ActorCountryStatItemDto {
  country: string = '';
  total: number = 0;
}

export class ActorCountryStatListDto {
  total: number = 0;
  list: ActorCountryStatItemDto[] = [];
}

export class EcoRankDto {
  eco_name: string = '';
  actors_total: number = 0;
  actors_new_total: number = 0;
  actors_core_total: number = 0;
  repos_total: number = 0;
  kind: string = '';
}

export class GetActorDateReqDto extends GetTotalReqDto {
  period: StatsPeriod = StatsPeriod.MONTH;
}

export class EcoRankListDto {
  list: EcoRankDto[] = [];
}

export class ActorDateListDto {
  list: ActorDateItemDto[] = [];
}

export class RepoRankListDto {
  list: QueryTopStarRepo[] = [];
}

export class ActorScoreRankListDto {
  list: QueryTopActor[] = [];
}

export class RepoActiveDevDto {
  list: GithubRepoDto[] = [];
}

export class GithubRepoDto {
  repo_id: number = 0;
}

export enum ReposOrderEnum {
  ID = 'id',
  ORG = 'org',
}

export enum DirectionEnum {
  ASC = 'asc',
  DESC = 'desc',
}

export class ReposOrderReqDto {
  order: ReposOrderEnum = ReposOrderEnum.ID;
  eco_name: EcoNameFilter = ECO_ALL;
  skip: number = 0;
  take: number = 100;
  direction: DirectionEnum = DirectionEnum.ASC;
  search: string | undefined;
}

export class RepoMarkDto {
  repo_id: number = 0;
  repo_name: string = '';
  upstream_marks: object = {};
  custom_marks: object = {};
}

export class GetReposMarkResDto {
  list: RepoMarkDto[] = [];
  total: number = 0;
}

export class LoginReqDto {
  type: string = 'github';
  code: string = '';
}

export class OpenBuildBindReqDto {
  code: string = '';
}

export class PrivyReqDto {
  id_token: string = '';
}

export class AuthBindWalletReqDto {
  address: string = '';
  magic: string = '';
  signature: string = '';
}

export class UpdateUserReqDto {
  user_nick_name?: string;
  user_avatar?: string;
  user_bio?: string;
  user_custom_x?: string;
  user_custom_labels?: Array<string>;
  user_title?: string;
  invite_code?: string;
}

export class UpdateUserExtraReqDto {
  user_extra: Record<string, unknown> = {};
}

export class ReposCustomMarkReqDto {
  eco_name: EcoNameFilter = ECO_ALL;
  mark: number = 1;
}

export class BaseIdReqAndResDto {
  id: number = 0;
}

export class SucessResDto {
  sucess: boolean = true;
}

export class EcoList {
  provider_ecosystem: string[] = [];
  available_ecosystem: string[] = [];
}

export enum Intent {
  Hackathon = 'hackathon',
  Profile = 'profile',
}

export class CustomQueryUsersReqDto {
  intent: Intent = Intent.Hackathon;
  request_data: string[] = [];
  description: string = '';
}

export class CustomQueryUsersOrderReqDto {
  skip: number = 0;
  intent: Intent = Intent.Hackathon;
  take: number = 10;
  direction: DirectionEnum = DirectionEnum.ASC;
}

export class CustomQueryUsersResDto {
  list: ApiAnalysisUsers[] = [];
  total: number = 0;
}

export class CustomUploadResDto {
  id: number = 0;
  users: GithubUsersDto[] | unknown[] = [];
  fail: string[] = [];
}

export class GithubUsersDto {
  login: string = '';
  id: number = 0;
  created_at: string = '';
  updated_at: string = '';
}

export class CustomShareReqDto {
  share: boolean = false;
}
