/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<
  string,
  bigint | number | string,
  bigint | number | string
>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _SqlxMigrations {
  checksum: Buffer;
  description: string;
  execution_time: Int8;
  installed_on: Generated<Timestamp>;
  success: boolean;
  version: Int8;
}

export interface AnalysisEcoEvent {
  created_at: Generated<Timestamp>;
  eco: Generated<string>;
  end_time: Generated<Timestamp>;
  id: Generated<Int8>;
  pr_count: Generated<number>;
  push_count: Generated<number>;
  start_time: Generated<Timestamp>;
  total_count: Generated<number>;
  uid: Generated<Int8>;
}

export interface AnalysisGithubPersonal {
  data: Generated<Json>;
  id: Generated<Int8>;
  login: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  _sqlx_migrations: _SqlxMigrations;
  'analysis.eco_event': AnalysisEcoEvent;
  'analysis.github_personal': AnalysisGithubPersonal;
}
