name: PR Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: ni --no-frozen-lockfile

      - name: Lint
        run: nr lint
